services:
  - type: web
    name: chatpilot
    env: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gthread -w 1 --threads 4 --bind 0.0.0.0:$PORT app:app